name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install boost
        run: sudo apt install libboost-all-dev

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Install graph tools
        run: bash graph.sh
      
      - name: Install cython
        run: pip install cython
      
      - name: Install dependencies
        run: pip install -r dev_requirments.txt

      
      - name: Test with pytest
        run: pytest tests